### ISSUE TITLE
Hide "Logged out" Container

### ISSUE THREAD

**Issue by TheAmazingLooser** [sgohlke/stackstream-chatviewer#2]
When using the Viewer, you're not logged in. This leaves a rather "ugly" message like:

Hello Chat 👋
Sign up to join the conversation.

in the Viewer all the time. Its not like it makes the viewer unusable but I personally think that without that Message the viewer does look a bit cleaner.
The container (div) does use a seperate CSS-Class which we can use. You could make it visibility: hidden or display: none.
```html
<div class="ant-row ant-row-center ant-row-middle signup-banner inner-space-16" style="row-gap: 0px;">
    <div class="ant-col ant-col-24">
        <h5 class="ant-typography next-title text-center type-default emit-margin-all">Hello Chat 👋</h5>
    </div>
    <div class="ant-col ant-col-24">
        <div class="ant-typography text-center" style="margin: 0px;"><a style="color: rgb(72, 189, 255);">Sign up</a> to join the conversation.</div>
    </div>
</div>
```
Hiding this div would be possible by using the `signup-banner`-CSS-Class!

**Comment by sgohlke** [comment]
Yes, it does not look good. I'll take a look and remove it in the next release.

**Comment by sgohlke** [comment]
Is available in release https://github.com/sgohlke/stackstream-chatviewer/releases/tag/v1.1.0 .
